dist: trusty

os:
  - linux

language: go

env: GO111MODULE=on GOFLAGS='-mod vendor

go:
  - "1.15"

sudo: false

services: mongodb

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - go get -u github.com/jstemmer/go-junit-report 
  - go vet ./... 
  - go build -race
  - go test ./... -race -v
