dist: trusty

os:
  - linux
  - osx

language: go

env: GO111MODULE=on GOFLAGS='-mod vendor

go:
  - "1.13"

sudo: false

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - go vet ./...
  - go test 
  - go build
  - go test ./... -v
