dist: xenial

language: go

env:
  global:
    - TRAVIS_GO_VERSION="$(cat .go-version)"

go:
  - master

git:
  depth: 1

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
